version: '3'

services:

  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:11.2.1-ce.0"
    restart: always
    hostname: "localhost"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        letsencrypt['enable'] = false
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    ##############################################################################
    ###   Volume is not working in docker windows with virutal machine here   ####
    ###   Uncomment this in production                                        ####
    ##############################################################################
    # volumes:
    #   - ./volumes/config:/etc/gitlab
    #   - ./volumes/logs:/var/log/gitlab
    #   - ./volumes/data:/var/opt/gitlab