version: '3'

services:
  nginx: 
    restart: always
    image: nginx:1.15.5-alpine
    container_name: nginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default/:/var/www/default
    ports:
      - 80:80
      - 443:443
